version: "3.7"
services:
  app: &app_base
    image: transcorr
    build:
      context: .
      args:
        - EXTRA_PACKAGES=less
        - FREEZE_BUNDLE=false
        - RACK_ENV=development
        - RUN_ASSETS_PRECOMPILE=false
        - RUN_MIGRATIONS=false
      target: builder
    command: bundle exec rails server -b 0.0.0 -p 3000
    hostname: transcorr-development-app
    stdin_open: true
    tty: true
    environment:
      - DOCKER_SERVICE=app
      - WEBPACKER_DEV_SERVER_HOST=webpacker
    env_file:
      - ./.env.local
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - .:/app
      - node_modules_folder:/app/node_modules
      - public_folder:/app/public
    depends_on:
      - webpacker
  webpacker:
    <<: *app_base
    command: bin/webpack-dev-server
    hostname: transcorr-development-webpack
    environment:
      - DOCKER_SERVICE=webpack
      - RACK_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    ports:
      - 3035:3035
    depends_on: []

volumes:
  node_modules_folder:
  public_folder:
